[package]
name = "mrecv"
version = "0.0.1"
authors = ["Miljan Karadzic <miljank@gmail.com>"]

[dependencies]
time = "0.1"
chrono = "0.4"
pnet_datalink = "0.21"
clap = { version = "2.32", features = ["yaml"] }
socket2 = { version = "0.3", features = ["reuseport"] }
